### ISSUE TITLE
save out subject ids in output file 

### ISSUE THREAD

**Issue by dpecheva** [cmig-research-group/cmig_tools#11]

**Comment by pierre-nedelec** [comment]
output `iid,eid` from `FEMA_wrapper`. Make a list that is the same size as design matrix list input

**Comment by pierre-nedelec** [comment]
actually, what do you need @dpecheva ? `iid` and `eid` are already saved in most cases in main output file.
Line 342 of `fema_wrapper`: 
```
      base_variables_to_save = {'X','iid','eid','colnames_model','contrasts','datatype','inputs','zmat','logpmat','beta_hat','beta_se','sig2mat','sig2tvec','save_params','mask'};
```

**Comment by dpecheva** [comment]
i think i must have an older version of FEMA, my base_variables_to_save is: 
      base_variables_to_save = {'X','colnames_model','contrasts','datatype','inputs','zmat','logpmat','beta_hat','beta_se','sig2mat','sig2tvec','save_params','mask'};

**Comment by dmysmith** [comment]
Try `git pull` and see if the outputs are how you want them! I just ran it and it seems like my results file contains eid and iid.

**Comment by dpecheva** [comment]
yep all good
