### ISSUE TITLE
Improve error message on missing values in ymat

### ISSUE THREAD

**Issue by evgeniiafrei** [cmig-research-group/cmig_tools#13]
I accidentaly called FEMA with ymat that had a few missing values. This fails with a crytic message while FEMA_fit internally tried to call FEMA_sig2binseg_parfeval. It would be better to test for missing values early on and raise a clear error message.

```
Error using zeros
NaN and Inf not allowed.

Error in FEMA_sig2binseg_parfeval (line 7)
nsig2bins = max(binvec); tvec_bins = zeros(nsig2bins,1);

Error in FEMA_fit (line 483)
                        [beta_hat beta_se betacon_hat betacon_se] = FEMA_sig2binseg_parfeval(X,ymat,contrasts,clusterinfo,binvec,sig2mat,sig2tvec,RandomEffects,GroupByFamType,nfamtypes,famtypevec,OLSflag,SingleOrDouble);
 
```

**Comment by parekhpravesh** [comment]
We now generate an error if either `X` or `ymat` have `NaN` or `Inf` [[93cbe05](https://github.com/cmig-research-group/cmig_tools_internal/commit/93cbe054ee6b38e1169dedefbb43de2d9227da9b)]
